/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `0_0` - 0_0 * `0_1` - 0_1 * `0_2` - 0_2 * `0_3` - 0_3 * `1_0` - 1_0 * `1_1` - 1_1 * `1_2` - 1_2 * `1_3` - 1_3
 */
export type PeriodEnum = '0_0' | '0_1' | '0_2' | '0_3' | '1_0' | '1_1' | '1_2' | '1_3';

export const PeriodEnum = {
    _00: '0_0' as PeriodEnum,
    _01: '0_1' as PeriodEnum,
    _02: '0_2' as PeriodEnum,
    _03: '0_3' as PeriodEnum,
    _10: '1_0' as PeriodEnum,
    _11: '1_1' as PeriodEnum,
    _12: '1_2' as PeriodEnum,
    _13: '1_3' as PeriodEnum
};

