/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PeriodEnum } from './periodEnum';
import { LazyReferenceField } from './lazyReferenceField';


/**
 * Serializer for EmbeddedDocuments.  Skips id field and uniqueness validation. When saving, skips calling instance.save
 */
export interface TechniqueMapper { 
    comment?: string;
    technique: LazyReferenceField;
    objective: LazyReferenceField;
    stage: Array<LazyReferenceField>;
    period: PeriodEnum;
}
export namespace TechniqueMapper {
}


